version: '3.8'

services:
  eureka-server:
    build: ./revpay-eureka-server
    image: revpay-eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  config-server:
    build: ./revpay-config-server
    image: revpay-config-server
    container_name: config-server
    ports:
      - "8888:8888"

  api-gateway:
    build: ./revpay-api-gateway
    image: revpay-api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - auth-service
      - user-service
      - wallet-service
      - notification-service
      - loan-service
      - invoice-service
      - analytics-service
      - admin-service
      - ai-service

  auth-service:
    build: ./revpay-auth-service
    image: revpay-auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  user-service:
    build: ./revpay-user-service
    image: revpay-user-service
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  wallet-service:
    build: ./revpay-wallet-service
    image: revpay-wallet-service
    container_name: wallet-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  notification-service:
    build: ./revpay-notification-service
    image: revpay-notification-service
    container_name: notification-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  loan-service:
    build: ./revpay-loan-service
    image: revpay-loan-service
    container_name: loan-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  invoice-service:
    build: ./revpay-invoice-service
    image: revpay-invoice-service
    container_name: invoice-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  analytics-service:
    build: ./revpay-analytics-service
    image: revpay-analytics-service
    container_name: analytics-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  admin-service:
    build: ./revpay-admin-service
    image: revpay-admin-service
    container_name: admin-service
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  ai-service:
    build: ./revpay-ai-service
    image: revpay-ai-service
    container_name: ai-service
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/revpay
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root1234
      - JWT_SECRET=AeExVfx68kU4nXib6ijdxqd5C6PRLzeIoiRhTiQ7lw8
    depends_on:
      - db
      - eureka-server

  db:
    image: mysql:8.0
    container_name: revpay-db
    environment:
      MYSQL_DATABASE: revpay
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - revpay_data:/var/lib/mysql

volumes:
  revpay_data:
