package com.revpay.enums;

public enum NotificationType {
    TRANSACTION_SENT,
    TRANSACTION_RECEIVED,
    MONEY_REQUEST_RECEIVED,
    MONEY_REQUEST_ACCEPTED,
    MONEY_REQUEST_DECLINED,
    MONEY_REQUEST_CANCELLED,
    CARD_ADDED,
    CARD_REMOVED,
    LOW_BALANCE,
    LOAN_APPROVED,
    LOAN_REJECTED,
    INVOICE_SENT,
    INVOICE_PAID,
    INVOICE_OVERDUE,
    GENERAL,
    SECURITY_ALERT,
    PROMOTIONAL,
    SYSTEM_UPDATE
}
